//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FridgeIngredient
    {
        public int Id { get; set; }
        public string UserProfileId { get; set; }
        public int IngredientId { get; set; }
        public double Amount { get; set; }
        public int MeasurementId { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
