//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListIngredient
    {
        public int Id { get; set; }
        public string UserProfileId { get; set; }
        public double Amount { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string RecipeTitle { get; set; }
        public string RecipeUrl { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
